update tamago shell script

diff --git a/new b/new
--- a/new
+++ b/new
@@ -1,5 +1,10 @@
 #!/bin/bash
-. .tamago
+. .tamago/shell
+
+if [ -f ${_META_DATA_} ]; then
+	. ${_META_DATA_}
+fi
+
 
 if [ $# -ne 1 ]; then
 	echo "Usage: $0 <new-map's-name>"
@@ -7,10 +12,43 @@ if [ $# -ne 1 ]; then
 	exit 1
 fi
 
+_FORCE_=0
+while getopts f OPT
+do
+	case ${OPT} in
+		"f" ) _FORCE_=1;;
+		* ) echo "Usage: $0 <map's-name>";
+		    echo "e.g.) $0 my-room";
+		    exit 1;;
+	esac
+done
 
+shift `expr $OPTIND - 1`
+_NEW_MAP_DIR_=${_DATA_DIR_}/${1}
 _TEMPLATE_DIR_=${_TEMPLATE_}
 
-_NEW_MAP_DIR_=${_DATA_DIR_}/${1}
+# check to be modified
+if [ ${_FORCE_} != "1" -a "${_CURRENT_WORKING_}" != "" ]; then
+	./${_CH_NEW_}
+	if [ $? = "1" ]; then
+		echo ""
+		echo "${_CURRENT_WORKING_} is modified."
+		while true
+		do 
+		        echo " Do you open ${_MAP_DIR_} without save? ... [y/n]"
+		        read yn
+
+		        if [ -z $yn ]; then 
+		                continue
+		        elif [ $yn = YES -o $yn = Yes -o $yn = yes -o $yn = Y -o $yn = y ]; then
+		                break
+		        elif [ $yn = NO -o $yn = No -o $yn = no -o $yn = N -o $yn = n ]; then
+			        echo " ... canceled"
+				exit 0
+		        fi
+		done 
+	fi
+fi
 
 
 if [ -d ${_NEW_MAP_DIR_} ]; then
@@ -28,83 +66,89 @@ else
 fi
 
 
-# opsm-position-tracker.conf
-_flg_pt_output_dir_=0
-_conf_pt_output_dir_=file-output-directory
-_flg_pt_opsm_map_=0
-_conf_pt_opsm_map_=opsm-map
-touch ${_NEW_MAP_DIR_}/${_P_TRACKER_CONF_}
-cat ${_TEMPLATE_DIR_}/${_P_TRACKER_CONF_} | while read line
-do
-	_line_pt_output_dir_=`echo "$line" | grep "${_conf_pt_output_dir_}" | wc -l`
-	_line_pt_opsm_map_=`echo "$line" | grep "${_conf_pt_opsm_map_}" | wc -l`
-	if [ ${_flg_pt_output_dir_} -eq 0 -a ${_line_pt_output_dir_} -eq 1 ]; then
-		echo "${_conf_pt_output_dir_} = ../${_NEW_MAP_DIR_}" >> ${_NEW_MAP_DIR_}/${_P_TRACKER_CONF_}
-		_flg_pt_output_dir_=1
-	elif [ ${_flg_pt_opsm_map_} -eq 0 -a ${_line_pt_opsm_map_} -eq 1 ]; then
-		echo "${_conf_pt_opsm_map_} = opsm-map" >> ${_NEW_MAP_DIR_}/${_P_TRACKER_CONF_}
-		_flg_pt_opsm_map_=1
-	else 
-		echo "${line}" >> ${_NEW_MAP_DIR_}/${_P_TRACKER_CONF_}
-	fi
-done
+# opsm-position-tracker
+if [ -f ${_TEMPLATE_DIR_}/${_P_TRACKER_CONF_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_P_TRACKER_CONF_} ${_NEW_MAP_DIR_}/
+	echo "${_P_TRACKER_CONF_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_P_TRACKER_CONF_} is not exist"
+fi
+
+# opsm-particle-evaluator
+if [ -f ${_TEMPLATE_DIR_}/${_P_EVALUATOR_CONF_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_P_EVALUATOR_CONF_} ${_NEW_MAP_DIR_}/
+	echo "${_P_TRACKER_CONF_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_P_EVALUATOR_CONF_} is not exist"
+fi
+
+# particle-localizer
+if [ -f ${_TEMPLATE_DIR_}/${_LOCLIZER_CONF_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_LOCLIZER_CONF_} ${_NEW_MAP_DIR_}/
+	echo "${_LOCLIZER_CONF_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_LOCLIZER_CONF_} is not exist"
+fi
+
+# path-planner
+if [ -f ${_TEMPLATE_DIR_}/${_PATH_PLAN_CONF_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_PATH_PLAN_CONF_} ${_NEW_MAP_DIR_}/
+	echo "${_PATH_PLAN_CONF_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_PATH_PLAN_CONF_} is not exist"
+fi
+if [ -f ${_TEMPLATE_DIR_}/${_PATH_PLAN_OPT_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_PATH_PLAN_OPT_} ${_NEW_MAP_DIR_}/${_PATH_PLAN_OPT_}
+	echo "${_PATH_PLAN_OPT_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_PATH_PLAN_OPT_} is not exist"
+fi
 
 
-# opsm-particle-evaluator.conf
-_flg_pe_map_dir_=0
-_conf_pe_map_dir_=cnt-map-dir
-touch ${_NEW_MAP_DIR_}/${_P_EVALUATOR_CONF_}
-cat ${_TEMPLATE_DIR_}/${_P_EVALUATOR_CONF_} | while read line
-do
-	_line_pe_map_dir_=`echo "$line" | grep "${_conf_pe_map_dir_}" | wc -l`
-	if [ ${_flg_pe_map_dir_} -eq 0 -a ${_line_pe_map_dir_} -eq 1 ]; then
-		echo "${_conf_pe_map_dir_} = ../${_NEW_MAP_DIR_}/opsm-map" >> ${_NEW_MAP_DIR_}/${_P_EVALUATOR_CONF_}
-		_flg_pe_map_dir_=1
-	else 
-		echo "${line}" >> ${_NEW_MAP_DIR_}/${_P_EVALUATOR_CONF_}
-	fi
-done
+# route-editor
+if [ -f ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_CONF_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_CONF_} ${_NEW_MAP_DIR_}/
+	echo "${_ROUTE_EDITOR_CONF_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_CONF_} is not exist"
+fi
+if [ -f ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_OPT_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_OPT_} ${_NEW_MAP_DIR_}/${_ROUTE_EDITOR_OPT_}
+	echo "${_ROUTE_EDITOR_OPT_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_ROUTE_EDITOR_OPT_} is not exist"
+fi
 
 
-# particle-localizer.conf
-touch ${_NEW_MAP_DIR_}/${_LOCLIZER_CONF_}
-cat ${_TEMPLATE_DIR_}/${_LOCLIZER_CONF_} | while read line
-do
-	echo "${line}" >> ${_NEW_MAP_DIR_}/${_LOCLIZER_CONF_}
-done
-
-# ysd-path-planner.conf
-touch ${_NEW_MAP_DIR_}/${_PATH_PLAN_CONF_}
-cat ${_TEMPLATE_DIR_}/${_PATH_PLAN_CONF_} | while read line
-do
-	echo "${line}" >> ${_NEW_MAP_DIR_}/${_PATH_PLAN_CONF_}
-done
-# ysd-path-planner.opt
-touch ${_NEW_MAP_DIR_}/${_PATH_PLAN_OPT_}
-echo -e "OPTION=\"-g ./${_PATH_PLAN_CONF_} -f ../${_NEW_MAP_DIR_}/keiro.dat -s\"" >> ${_NEW_MAP_DIR_}/${_PATH_PLAN_OPT_}
-
-# tkg-route-editor/path.conf
-touch ${_NEW_MAP_DIR_}/${_ROUTE_EDITOR_CONF_}
-echo -e -n "../${_DATA_DIR_}\n" >> ${_NEW_MAP_DIR_}/${_ROUTE_EDITOR_CONF_}
-# tkg-route-editor.opt
-touch ${_NEW_MAP_DIR_}/${_ROUTE_EDITOR_OPT_}
-echo -e "OPTION=\"-m ${1}\"\n" >> ${_NEW_MAP_DIR_}/${_ROUTE_EDITOR_OPT_}
-
-# visualizer.conf
-touch ${_NEW_MAP_DIR_}/${_VISUALIZER_CONF_}
-echo "../${_NEW_MAP_DIR_}/opsm-map" >> ${_NEW_MAP_DIR_}/${_VISUALIZER_CONF_}
-
-# tkg-route-editor/path.conf
-cp ${_TEMPLATE_DIR_}/${_FRONT_LS_CCONVERTER_CONF_} ${_NEW_MAP_DIR_}/
-# tkg-route-editor/path.conf
-cp ${_TEMPLATE_DIR_}/${_V_LS_CCONVERTER_CONF_} ${_NEW_MAP_DIR_}/
-# tkg-route-editor.opt
-touch ${_NEW_MAP_DIR_}/${_LS_CCONVERTER_OPT_}
-echo -e "OPTION=\"-g ${_LS_CCONVERTER_CONF_}\"\n" >> ${_NEW_MAP_DIR_}/${_LS_CCONVERTER_OPT_}
-
-# multilogger
-cp ${_TEMPLATE_DIR_}/${_LOGGING_LIST_} ${_NEW_MAP_DIR_}/
+# visualizer
+# if [ -f ${_TEMPLATE_DIR_}/${_VISUALIZER_CONF_} ]; then
+# 	cp ${_TEMPLATE_DIR_}/${_VISUALIZER_CONF_} ${_NEW_MAP_DIR_}/
+# 	echo "${_VISUALIZER_CONF_} ... ok"
+# else 
+# 	echo "Error: ${_TEMPLATE_DIR_}/${_VISUALIZER_CONF_} is not exist"
+# fi
 
 
-./${_OPEN_} ${_NEW_MAP_DIR_}
+# ls-coordinate-converter
+if [ -f ${_TEMPLATE_DIR_}/${_FRONT_LS_CCONVERTER_CONF_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_FRONT_LS_CCONVERTER_CONF_} ${_NEW_MAP_DIR_}/
+	echo "${_FRONT_LS_CCONVERTER_CONF_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_FRONT_LS_CCONVERTER_CONF_} is not exist"
+fi
+if [ -f ${_TEMPLATE_DIR_}/${_V_LS_CCONVERTER_CONF_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_V_LS_CCONVERTER_CONF_} ${_NEW_MAP_DIR_}/
+	echo "${_V_LS_CCONVERTER_CONF_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_V_LS_CCONVERTER_CONF_} is not exist"
+fi
+if [ -f ${_TEMPLATE_DIR_}/${_LS_CCONVERTER_OPT_} ]; then
+	cp ${_TEMPLATE_DIR_}/${_LS_CCONVERTER_OPT_} ${_NEW_MAP_DIR_}/${_LS_CCONVERTER_OPT_}
+	echo "${_LS_CCONVERTER_OPT_} ... ok"
+else 
+	echo "Error: ${_TEMPLATE_DIR_}/${_LS_CCONVERTER_OPT_} is not exist"
+fi
+
+
+./${_OPEN_} -f ${_NEW_MAP_DIR_}
 
